import { Architecture } from "../models/Architecture";
import { ProjectScanResult } from "./ProjectScanner";


export class ArchitectureBuilder {



	static build(

		scan:ProjectScanResult,

		analysis:any

	):Architecture {



		const modules =

		analysis?.modules ??

		[];




		return {



			projectName:

			scan.rootPath.split("\\").pop()
			??

			"Unknown Project",





			description:

			analysis?.summary
			??

			"",





			vision:

			analysis?.summary
			??

			"Generated by Project Brain",





			technologyStack:

			scan.technologies,





			modules:

			modules.map(

				(module:any,index:number)=>({



					id:

					"module_" +

					(index+1),




					name:

					module.name
					??

					"Unknown",




					description:

					module.description
					??

					"",




					status:

					module.status
					??

					"PLANNED",




					progress:0,




					dependsOn:[],




					files:[]



				})

			),






			roadmap:[


				{


					id:"PB-001",


					title:

					"Validate generated architecture",



					description:

					"Review AI generated modules and approve structure",



					status:"TODO",



					dependsOn:[]



				}


			],




			decisions:[],




			risks:

			analysis?.risks
			??

			[],





			ideas:

			[],




			createdAt:

			new Date()

			.toISOString(),




			updatedAt:

			new Date()

			.toISOString()


		};


	}



}