import { ProjectScanResult } from "./ProjectScanner";
import { Architecture } from "../models/Architecture";



export class ArchitectureService {



	createFromScan(

		scan:ProjectScanResult,

		description:string = ""

	):Architecture {



		return {


			projectName:

			scan.rootPath.split("\\").pop()
			??

			"Unknown Project",



			description,



			vision:

			description || 
			"Project generated by Project Brain",




			technologyStack:

			scan.technologies,




			modules:

			[],




			roadmap:[


				{

					id:"PB-001",

					title:"Review generated architecture",

					description:
					"User validates AI generated modules",

					status:"TODO",

					dependsOn:[]

				}

			],





			decisions:[],



			risks:[],



			ideas:[],




			createdAt:

			new Date()

			.toISOString(),




			updatedAt:

			new Date()

			.toISOString()


		};



	}



}